import CoreGraphics
import Foundation

final class GraphicObjectStore {
    private(set) var objects: [GraphicObject] = []
    var isEmpty: Bool { objects.isEmpty }
    func clear() { objects.removeAll(keepingCapacity: true) }

    @discardableResult func addLine(from start: CGPoint, to end: CGPoint, style: GraphicObject.Style) -> UUID { let object = GraphicObject.line(from: start, to: end, style: style); objects.append(object); return object.id }
    @discardableResult func addPolygon(points: [CGPoint], style: GraphicObject.Style) -> UUID { let object = GraphicObject.polygon(points: points, style: style); objects.append(object); return object.id }
    @discardableResult func addDynamicAngle(vertex: CGPoint, startLength: CGFloat = 180, endLength: CGFloat = 180, angleDegrees: CGFloat = 45, minimum: CGFloat = 10, maximum: CGFloat = 170, step: CGFloat = 1, name: String = "α", style: GraphicObject.Style = GraphicObject.Style()) -> UUID { let object = DynamicAngleFactory.makeGraphicObject(vertex: vertex, startLength: startLength, endLength: endLength, angleDegrees: angleDegrees, minimum: minimum, maximum: maximum, step: step, name: name, style: style); objects.append(object); return object.id }
    @discardableResult func addIsoscelesTriangle(anchor: CGPoint, legLength: CGFloat = 150, apexAngleDegrees: CGFloat = 60, style: GraphicObject.Style = GraphicObject.Style()) -> UUID { let object = GraphicObject.isoscelesTriangle(anchor: anchor, legLength: legLength, apexAngleDegrees: apexAngleDegrees, style: style); objects.append(object); return object.id }
    @discardableResult func addDynamicIsoscelesTriangle(anchor: CGPoint, legLength: CGFloat = 150, apexAngleDegrees: CGFloat = 60, minimum: CGFloat = 30, maximum: CGFloat = 150, step: CGFloat = 1, style: GraphicObject.Style = GraphicObject.Style()) -> UUID { let dynamic = DynamicIsoscelesTriangle(anchor: anchor, legLength: legLength, apexAngleDegrees: apexAngleDegrees, minimum: minimum, maximum: maximum, step: step); objects.append(dynamic.graphicObject(style: style)); return dynamic.id }
    func insert(_ object: GraphicObject) { objects.append(object) }
    func object(with id: UUID) -> GraphicObject? { objects.first { $0.id == id } }
    func update(_ object: GraphicObject) { guard let index=objects.firstIndex(where:{$0.id==object.id}) else { objects.append(object); return }; objects[index]=object }
    func remove(id: UUID) { objects.removeAll { $0.id == id } }

    func transformedPoints(of object: GraphicObject) -> [CGPoint] { if object.kind == .parameterizedTriangle, let triangle=object.triangleModel { return triangle.vertices().map { transformedPoint($0,in:object) } }; if object.kind == .dynamicAngle, let dynamicAngle=object.dynamicAngleModel { return dynamicAngle.model.points.map { transformedPoint(CGPoint(x: $0.position.x, y: $0.position.y), in: object) } }; return object.geometry.points.map { transformedPoint($0,in:object) } }
    func transformedPoints(of id: UUID) -> [CGPoint]? { guard let object=object(with:id) else{return nil}; return transformedPoints(of:object) }

    @discardableResult func updateTriangleModel(id: UUID,_ update:(inout ParameterizedTriangle)->Void)->Bool { guard let i=objects.firstIndex(where:{$0.id==id}),objects[i].kind == .parameterizedTriangle,var m=objects[i].triangleModel else{return false};update(&m);objects[i].triangleModel=m;objects[i].geometryModel=nil;objects[i].geometry.points=m.vertices();return true }
    @discardableResult func dragTriangleVertex(id:UUID,vertexIndex:Int,to point:CGPoint)->Bool { guard let i=objects.firstIndex(where:{$0.id==id}),objects[i].kind == .parameterizedTriangle,var m=objects[i].triangleModel else{return false};guard GeometryInteractionEngine.dragTriangle(&m,vertexIndex:vertexIndex,to:point) else{return false};objects[i].triangleModel=m;objects[i].geometry.points=m.vertices();return true }
    @discardableResult func setTriangleParameter(id:UUID,parameter:TriangleParameter,value:CGFloat)->Bool { guard let i=objects.firstIndex(where:{$0.id==id}),objects[i].kind == .parameterizedTriangle,var m=objects[i].triangleModel else{return false};GeometryInteractionEngine.setTriangleParameter(&m,parameter:parameter,value:value);objects[i].triangleModel=m;objects[i].geometry.points=m.vertices();return true }
    func triangleParameter(id:UUID)->CGFloat? { guard let o=object(with:id),o.kind == .parameterizedTriangle,let m=o.triangleModel else{return nil}; return m.apexAngleDegrees }
    func triangleLegLength(id: UUID) -> CGFloat? { guard let o=object(with:id),o.kind == .parameterizedTriangle,let m=o.triangleModel else{return nil}; return m.legLength }
    func triangleLegLengthControlPoint(id: UUID) -> CGPoint? { guard let o=object(with:id),o.kind == .parameterizedTriangle,let m=o.triangleModel else{return nil}; return transformedPoint(m.legLengthControlPoint(), in:o) }
    @discardableResult func setDynamicTriangleAngle(id: UUID,degrees:CGFloat)->Bool { guard let i=objects.firstIndex(where:{$0.id==id}),objects[i].kind == .parameterizedTriangle,var m=objects[i].triangleModel else{return false};m.setApexAngle(degrees);objects[i].triangleModel=m;objects[i].geometry.points=m.vertices();return true }
    @discardableResult func setDynamicTriangleLegLength(id: UUID,length:CGFloat)->Bool { guard let i=objects.firstIndex(where:{$0.id==id}),objects[i].kind == .parameterizedTriangle,var m=objects[i].triangleModel else{return false};m.setLegLength(length);objects[i].triangleModel=m;objects[i].geometry.points=m.vertices();return true }
    @discardableResult func dragDynamicTriangleLegLengthControl(id: UUID,to point:CGPoint)->Bool { guard let i=objects.firstIndex(where:{$0.id==id}),objects[i].kind == .parameterizedTriangle,var m=objects[i].triangleModel else{return false};let raw=inverseTransform(point,in:objects[i]);guard let length=m.legLength(forControlPoint:raw),length.isFinite else{return false};m.setLegLength(length);objects[i].triangleModel=m;objects[i].geometry.points=m.vertices();return true }
    @discardableResult func dragDynamicTriangleVertex(id: UUID,vertexIndex:Int,to point:CGPoint)->Bool { guard let i=objects.firstIndex(where:{$0.id==id}),objects[i].kind == .parameterizedTriangle,var m=objects[i].triangleModel else{return false};guard GeometryInteractionEngine.dragTriangle(&m,vertexIndex:vertexIndex,to:point) else{return false};objects[i].triangleModel=m;objects[i].geometry.points=m.vertices();return true }
    func dynamicTriangleSnapshot(id: UUID)->(angle:CGFloat,legLength:CGFloat,vertices:[CGPoint])? { guard let o=object(with:id),o.kind == .parameterizedTriangle,let m=o.triangleModel else{return nil};return(m.apexAngleDegrees,m.legLength,m.vertices()) }
    @discardableResult func setDynamicAngle(id:UUID,degrees:CGFloat)->Bool { guard let i=objects.firstIndex(where:{$0.id==id}),objects[i].kind == .dynamicAngle,var m=objects[i].dynamicAngleModel else{return false};guard m.setAngle(degrees) else{return false};objects[i].dynamicAngleModel=m;objects[i].geometryModel=m.model;return true }
    func dynamicAngleParameter(id:UUID)->GeometryParameter? { guard let o=object(with:id),o.kind == .dynamicAngle,let m=o.dynamicAngleModel else{return nil};return m.parameter }
    @discardableResult func dragDynamicAngleEndpoint(id:UUID,to point:CGPoint)->Bool { guard let i=objects.firstIndex(where:{$0.id==id}),objects[i].kind == .dynamicAngle,var m=objects[i].dynamicAngleModel else{return false};guard let ei=m.model.points.firstIndex(where:{$0.id==m.endPointID}),!m.model.points[ei].isFixed,let v=m.model.points.first(where:{$0.id==m.vertexPointID}),let s=m.model.points.first(where:{$0.id==m.startPointID}) else{return false};let dx=point.x-v.position.x,dy=point.y-v.position.y;guard hypot(dx,dy)>0.001 else{return false};let sx=s.position.x-v.position.x,sy=s.position.y-v.position.y;let degrees=min(170,max(10,atan2(abs(sx*dy-sy*dx),sx*dx+sy*dy)*180 / .pi));guard m.setAngle(degrees) else{return false};objects[i].dynamicAngleModel=m;objects[i].geometryModel=m.model;return true }

    func nearestLineEndpoint(to point:CGPoint,tolerance:CGFloat=12)->(id:UUID,endpoint:Int,distance:CGFloat)? { var best:(id:UUID,endpoint:Int,distance:CGFloat)?;for o in objects where o.kind == .line {guard o.geometry.points.count>=2 else{continue};for e in 0...1{let p=transformedPoint(o.geometry.points[e],in:o),d=hypot(p.x-point.x,p.y-point.y);if d<=tolerance&&(best == nil || d<best!.distance){best=(o.id,e,d)}}};for o in objects where o.kind == .parameterizedTriangle {guard let model=o.triangleModel else{continue};let p=transformedPoint(model.legLengthControlPoint(),in:o),d=hypot(p.x-point.x,p.y-point.y);if d<=tolerance&&(best == nil || d<best!.distance){best=(o.id,0,d)}};return best }
    func nearestPolygonVertex(to point:CGPoint,tolerance:CGFloat=12)->(id:UUID,index:Int,distance:CGFloat)? { var best:(id:UUID,index:Int,distance:CGFloat)?;for o in objects where o.kind == .polygon {for(i,raw) in o.geometry.points.enumerated(){let p=transformedPoint(raw,in:o),d=hypot(p.x-point.x,p.y-point.y);if d<=tolerance&&(best == nil || d<best!.distance){best=(o.id,i,d)}}};return best }
    @discardableResult func movePolygonVertex(id:UUID,index:Int,to point:CGPoint)->Bool { guard let i=objects.firstIndex(where:{$0.id==id}),objects[i].kind == .polygon,objects[i].geometry.points.indices.contains(index) else{return false};objects[i].geometry.points[index]=point;return true }

    func bounds(of id:UUID)->CGRect?{guard let o=object(with:id) else{return nil};return bounds(of:o)}
    func bounds(of object:GraphicObject)->CGRect? { switch object.kind {case .group:return object.children.compactMap(bounds(of:)).reduce(nil){$0?.union($1) ?? $1};case .rectangle,.ellipse,.coordinateSystem,.functionGraph:let p1=transformedPoint(CGPoint(x:object.geometry.x,y:object.geometry.y),in:object),p2=transformedPoint(CGPoint(x:object.geometry.x+object.geometry.width,y:object.geometry.y+object.geometry.height),in:object);return CGRect(x:min(p1.x,p2.x),y:min(p1.y,p2.y),width:abs(p2.x-p1.x),height:abs(p2.y-p1.y)).insetBy(dx:-max(1,object.style.strokeWidth),dy:-max(1,object.style.strokeWidth));default:let p=transformedPoints(of:object);guard let f=p.first else{return nil};var r=CGRect(origin:f,size:.zero);for q in p.dropFirst(){r=r.union(CGRect(origin:q,size:.zero))};return r.insetBy(dx:-max(1,object.style.strokeWidth),dy:-max(1,object.style.strokeWidth))} }
    func hitTest(at point:CGPoint,tolerance:CGFloat=10)->UUID?{for o in objects.reversed() where hitTest(o,at:point,tolerance:tolerance){return o.id};return nil}
    private func hitTest(_ o:GraphicObject,at point:CGPoint,tolerance:CGFloat)->Bool{let t=tolerance+o.style.strokeWidth;switch o.kind{case .geometryPoint:guard let p=transformedPoints(of:o).first else{return false};return hypot(p.x-point.x,p.y-point.y)<=t;case .line,.arrow,.parameterizedTriangle,.dynamicAngle:let p=transformedPoints(of:o);guard p.count>=2 else{return false};let q=o.kind == .parameterizedTriangle ? Array(p.dropFirst())+[p[0]]:Array(p.dropFirst());return zip(p,q).contains{distance(point,toSegment:$0.0,$0.1)<=t};case .polygon:let p=transformedPoints(of:o);guard p.count>=3 else{return false};return pointInPolygon(point,p)||zip(p,Array(p.dropFirst())+[p[0]]).contains{distance(point,toSegment:$0.0,$0.1)<=t};case .rectangle,.ellipse:guard let r=bounds(of:o) else{return false};if o.kind == .rectangle{return r.insetBy(dx:-t,dy:-t).contains(point)};let cx=r.midX,cy=r.midY,rx=max(r.width/2,0.001),ry=max(r.height/2,0.001);return pow((point.x-cx)/rx,2)+pow((point.y-cy)/ry,2)<=1+t/max(rx,ry);case .freehandStroke:let p=transformedPoints(of:o);return zip(p,p.dropFirst()).contains{distance(point,toSegment:$0.0,$0.1)<=t};case .coordinateSystem,.functionGraph:return bounds(of:o)?.insetBy(dx:-t,dy:-t).contains(point) ?? false;case .group:return o.children.contains{hitTest($0,at:point,tolerance:tolerance)}}}
    func objectsIntersecting(_ rect:CGRect,fullyContained:Bool=false)->[UUID]{objects.compactMap{guard let b=bounds(of:$0) else{return nil};return(fullyContained ? rect.contains(b):rect.intersects(b)) ? $0.id:nil}}
    func objectsHitByScribble(_ path:[CGPoint],tolerance:CGFloat=12)->[UUID]{guard path.count>=2 else{return[]};return objects.filter{guard let b=bounds(of:$0) else{return false};let e=b.insetBy(dx:-tolerance,dy:-tolerance);return path.contains(where:e.contains)||zip(path,path.dropFirst()).contains{e.intersects(segmentBounds($0,$1))}}.map(\.id)}
    func objectsIntersectingLasso(_ lasso:[CGPoint])->[UUID]{guard lasso.count>=3 else{return[]};return objects.compactMap{guard let b=bounds(of:$0) else{return nil};let c=[CGPoint(x:b.minX,y:b.minY),CGPoint(x:b.maxX,y:b.minY),CGPoint(x:b.maxX,y:b.maxY),CGPoint(x:b.minX,y:b.maxY),CGPoint(x:b.midX,y:b.midY)];return c.contains(where:{pointInPolygon($0,lasso)}) ? $0.id:nil}}
    @discardableResult func eraseByScribble(_ path:[CGPoint],tolerance:CGFloat=12)->[UUID]{let ids=Set(objectsHitByScribble(path,tolerance:tolerance));guard !ids.isEmpty else{return[]};objects.removeAll{ids.contains($0.id)};return Array(ids)}

    @discardableResult
    func moveLineEndpoint(id:UUID,endpoint:Int,to point:CGPoint)->Bool {
        if let o=object(with:id),o.kind == .parameterizedTriangle && endpoint == 0 { return dragDynamicTriangleLegLengthControl(id:id,to:point) }
        return moveLineEndpointResolved(id:id,endpoint:endpoint,to:point)
    }

    @discardableResult
    func transform(id:UUID,position:CGPoint?=nil,scale:CGSize?=nil,rotation:CGFloat?=nil)->Bool{guard let i=objects.firstIndex(where:{$0.id==id}) else{return false};if let position{objects[i].transform.position=position};if let scale{objects[i].transform.scale=scale};if let rotation{objects[i].transform.rotation=rotation};return true}
    func exportObjects()->[GraphicObject]{objects};func importObjects(_ value:[GraphicObject]){objects=value}

    private func transformedPoint(_ point:CGPoint,in object:GraphicObject)->CGPoint{let c=object.transform.rotationCenter,t=CGPoint(x:point.x-c.x,y:point.y-c.y),s=CGPoint(x:t.x*object.transform.scale.width,y:t.y*object.transform.scale.height),co=cos(object.transform.rotation),si=sin(object.transform.rotation);return CGPoint(x:s.x*co-s.y*si+c.x+object.transform.position.x,y:s.x*si+s.y*co+c.y+object.transform.position.y)}
    private func inverseTransform(_ point:CGPoint,in object:GraphicObject)->CGPoint {
        let p=CGPoint(x:point.x-object.transform.position.x-object.transform.rotationCenter.x,y:point.y-object.transform.position.y-object.transform.rotationCenter.y)
        let co=cos(object.transform.rotation),si=sin(object.transform.rotation)
        let rx=p.x*co+p.y*si
        let ry=(-p.x*si)+(p.y*co)
        let sx=abs(object.transform.scale.width)>0.0001 ? rx/object.transform.scale.width : rx
        let sy=abs(object.transform.scale.height)>0.0001 ? ry/object.transform.scale.height : ry
        return CGPoint(x:sx+object.transform.rotationCenter.x,y:sy+object.transform.rotationCenter.y)
    }
    private func segmentBounds(_ a:CGPoint,_ b:CGPoint)->CGRect{CGRect(x:min(a.x,b.x),y:min(a.y,b.y),width:abs(b.x-a.x),height:abs(b.y-a.y))}
    private func distance(_ p:CGPoint,toSegment a:CGPoint,_ b:CGPoint)->CGFloat{let dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if l==0{return hypot(p.x-a.x,p.y-a.y)};let t=max(0,min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l)),q=CGPoint(x:a.x+t*dx,y:a.y+t*dy);return hypot(p.x-q.x,p.y-q.y)}
    private func pointInPolygon(_ p:CGPoint,_ poly:[CGPoint])->Bool{guard poly.count>=3 else{return false};var inside=false;var j=poly.count-1;for i in poly.indices{let a=poly[i],b=poly[j];if(a.y>p.y) != (b.y>p.y){let d=b.y-a.y;if d != 0{let x=(b.x-a.x)*(p.y-a.y)/d+a.x;if p.x<x{inside.toggle()}}};j=i};return inside}
}