import Foundation
import Metal
import MetalKit
import simd

final class InkRenderer: NSObject, MTKViewDelegate {
    enum SelectionHandle { case topRight, bottomRight }
    private struct Uniforms { var viewportSize: SIMD2<Float> }
    private struct StoredStroke: Equatable { var id: UUID; var points: [InkPoint]; var style: PenStyle; var rotation: Float = 0 }
    private struct HistoryState { var strokes: [StoredStroke]; var objects: [GraphicObject]; var selection: [Int]; var objectSelection: [UUID] }

    private let device: any MTLDevice
    private let commandQueue: any MTLCommandQueue
    private let pipelineState: any MTLRenderPipelineState
    private var committedStrokes: [StoredStroke] = []
    private var objectStore = GraphicObjectStore()
    private var activeStroke: [InkPoint] = []
    private var vertices: [InkVertex] = []
    private var vertexBuffer: (any MTLBuffer)?
    private var uniformBuffer: (any MTLBuffer)?
    private var penStyle = PenStyle()
    private(set) var selectedStrokeIndices: [Int] = []
    private(set) var selectedObjectIDs: [UUID] = []
    private var customRotationCenter: SIMD2<Float>?
    private var backgroundColor = SIMD4<Float>(1, 1, 1, 1)
    private var displayInverted = false
    private var backgroundPattern = 0
    private var panOffset = SIMD2<Float>(0, 0)
    private var zoomScale: Float = 1
    private var undoStack: [HistoryState] = []
    private var redoStack: [HistoryState] = []
    private var transactionStart: HistoryState?
    private var pasteCascadeIndex = 0
    private var lastClipboardPayloadData: Data?
    private var dynamicAngleAnimationDriver = GeometryParameterAnimationDriver()
    private var animationTimer: Timer?
    private weak var attachedView: MTKView?

    init?(device: any MTLDevice) {
        guard let queue = device.makeCommandQueue(), let library = try? device.makeDefaultLibrary(bundle: Bundle.module), let vf = library.makeFunction(name: "inkVertex"), let ff = library.makeFunction(name: "inkFragment") else { return nil }
        let descriptor = MTLRenderPipelineDescriptor()
        descriptor.vertexFunction = vf; descriptor.fragmentFunction = ff; descriptor.colorAttachments[0].pixelFormat = .bgra8Unorm
        descriptor.colorAttachments[0].isBlendingEnabled = true
        descriptor.colorAttachments[0].sourceRGBBlendFactor = .sourceAlpha; descriptor.colorAttachments[0].destinationRGBBlendFactor = .oneMinusSourceAlpha
        descriptor.colorAttachments[0].sourceAlphaBlendFactor = .sourceAlpha; descriptor.colorAttachments[0].destinationAlphaBlendFactor = .oneMinusSourceAlpha
        guard let pipeline = try? device.makeRenderPipelineState(descriptor: descriptor) else { return nil }
        self.device = device; self.commandQueue = queue; self.pipelineState = pipeline; super.init()
    }
    deinit { animationTimer?.invalidate() }

    var canUndo: Bool { !undoStack.isEmpty }
    var canRedo: Bool { !redoStack.isEmpty }
    var hasSelection: Bool { !selectedStrokeIndices.isEmpty || !selectedObjectIDs.isEmpty }
    var selectionCount: Int { selectedStrokeIndices.count + selectedObjectIDs.count }
    var selectedStrokeIndex: Int? { selectedObjectIDs.isEmpty && selectedStrokeIndices.count == 1 ? selectedStrokeIndices[0] : nil }
    var zoomPercent: Int { Int((zoomScale * 100).rounded()) }
    var selectedRotationDegrees: Double {
        if selectedObjectIDs.count == 1, let id = selectedObjectIDs.first, let object = objectStore.object(with: id) { return Double(object.transform.rotation) * 180 / Double.pi }
        guard let index = selectedStrokeIndex, committedStrokes.indices.contains(index) else { return 0 }
        return Double(committedStrokes[index].rotation) * 180 / Double.pi
    }

    func setPenStyle(_ style: PenStyle) { penStyle = style; rebuildGeometry() }
    func setBackgroundColor(_ color: SIMD4<Float>) { backgroundColor = color; rebuildGeometry() }
    func setDisplayInverted(_ value: Bool) { displayInverted = value; rebuildGeometry() }
    func setBackgroundPattern(_ value: Int) { backgroundPattern = value; rebuildGeometry() }
    func setStroke(_ points: [InkPoint]) { activeStroke = points; rebuildGeometry() }
    func canvasPoint(from point: SIMD2<Float>) -> SIMD2<Float> { (point - panOffset) / zoomScale }
    func viewPoint(from point: SIMD2<Float>) -> SIMD2<Float> { point * zoomScale + panOffset }
    func pan(by delta: SIMD2<Float>) { panOffset += delta; rebuildGeometry() }
    func zoom(by factor: Float, around point: SIMD2<Float>) { let c = canvasPoint(from: point); zoomScale = min(max(zoomScale * factor, 0.25), 4); panOffset = point - c * zoomScale; rebuildGeometry() }
    func resetZoom(centeredIn size: CGSize) { zoomScale = 1; panOffset = SIMD2(Float(size.width / 2), Float(size.height / 2)); rebuildGeometry() }

    func exportPageState() -> CanvasPageState { CanvasPageState(strokes: committedStrokes.map { CanvasStroke(id: $0.id, points: $0.points, style: $0.style, rotation: $0.rotation) }, objects: objectStore.exportObjects()) }
    func importPageState(_ state: CanvasPageState) { stopAllDynamicAngleAnimations(); committedStrokes = state.strokes.map { StoredStroke(id: $0.id, points: $0.points, style: $0.style, rotation: $0.rotation) }; objectStore.importObjects(state.objects); activeStroke = []; selectedStrokeIndices = []; selectedObjectIDs = []; customRotationCenter = nil; undoStack = []; redoStack = []; transactionStart = nil; pasteCascadeIndex = 0; lastClipboardPayloadData = nil; rebuildGeometry() }
    func beginHistoryTransaction() { if transactionStart == nil { transactionStart = captureState() } }
    func endHistoryTransaction() { guard let before = transactionStart else { return }; transactionStart = nil; let after = captureState(); if before.strokes != after.strokes || before.objects != after.objects || before.selection != after.selection || before.objectSelection != after.objectSelection { undoStack.append(before); redoStack.removeAll() } }
    private func recordMutation() { guard transactionStart == nil else { return }; undoStack.append(captureState()); redoStack.removeAll() }
    private func captureState() -> HistoryState { HistoryState(strokes: committedStrokes, objects: objectStore.exportObjects(), selection: selectedStrokeIndices, objectSelection: selectedObjectIDs) }
    private func restore(_ state: HistoryState) { committedStrokes = state.strokes; objectStore.importObjects(state.objects); selectedStrokeIndices = state.selection.filter { committedStrokes.indices.contains($0) }; selectedObjectIDs = state.objectSelection.filter { objectStore.object(with: $0) != nil }; customRotationCenter = nil; rebuildGeometry() }
    func undo() { guard let state = undoStack.popLast() else { return }; redoStack.append(captureState()); restore(state) }
    func redo() { guard let state = redoStack.popLast() else { return }; undoStack.append(captureState()); restore(state) }

    func commitStroke(_ points: [InkPoint]) { guard points.count >= 2 else { activeStroke = []; rebuildGeometry(); return }; recordMutation(); committedStrokes.append(StoredStroke(id: UUID(), points: points, style: penStyle)); selectedStrokeIndices = []; selectedObjectIDs = []; activeStroke = []; rebuildGeometry() }
    func commitLine(from start: SIMD2<Float>, to end: SIMD2<Float>) { recordMutation(); let style = GraphicObject.Style(strokeColor: penStyle.color, strokeWidth: penStyle.width, opacity: penStyle.opacity, lineStyle: penStyle.lineStyle, fillEnabled: false, fillColor: .black, fillOpacity: 0); _ = objectStore.addLine(from: CGPoint(x: CGFloat(start.x), y: CGFloat(start.y)), to: CGPoint(x: CGFloat(end.x), y: CGFloat(end.y)), style: style); selectedStrokeIndices = []; selectedObjectIDs = []; activeStroke = []; rebuildGeometry() }
    func commitPolygon(points: [CGPoint]) { guard points.count >= 3 else { return }; recordMutation(); let style = GraphicObject.Style(strokeColor: penStyle.color, strokeWidth: penStyle.width, opacity: penStyle.opacity, lineStyle: penStyle.lineStyle, fillEnabled: false, fillColor: .black, fillOpacity: 0); _ = objectStore.addPolygon(points: points, style: style); selectedStrokeIndices = []; selectedObjectIDs = []; activeStroke = []; rebuildGeometry() }

    // MARK: - Dynamic angle
    @discardableResult func commitDynamicAngle(at viewPoint: SIMD2<Float>, angleDegrees: CGFloat = 45) -> UUID {
        let canvas = canvasPoint(from: viewPoint); recordMutation()
        let style = GraphicObject.Style(strokeColor: penStyle.color, strokeWidth: penStyle.width, opacity: penStyle.opacity, lineStyle: penStyle.lineStyle, fillEnabled: false, fillColor: .black, fillOpacity: 0)
        let id = objectStore.addDynamicAngle(vertex: CGPoint(x: CGFloat(canvas.x), y: CGFloat(canvas.y)), startLength: 150 / CGFloat(zoomScale), endLength: 150 / CGFloat(zoomScale), angleDegrees: angleDegrees, minimum: 10, maximum: 170, step: 1, name: "α", style: style)
        selectedStrokeIndices = []; selectedObjectIDs = [id]; activeStroke = []; rebuildGeometry(); return id
    }
    @discardableResult func dynamicAngleEndpoint(at point: SIMD2<Float>, tolerance: Float = 16) -> UUID? { let p = canvasPoint(from: point); let t = CGFloat(tolerance / zoomScale); var best: CGFloat = .greatestFiniteMagnitude; var hit: UUID?; for object in objectStore.objects where object.kind == .dynamicAngle { guard let model = object.dynamicAngleModel, let endpoint = model.model.points.first(where: { $0.id == model.endPointID }) else { continue }; let d = hypot(endpoint.position.x - CGFloat(p.x), endpoint.position.y - CGFloat(p.y)); if d <= t && d < best { best = d; hit = object.id } }; return hit }
    @discardableResult func moveDynamicAngleEndpoint(id: UUID, to viewPoint: SIMD2<Float>) -> Bool { let p = canvasPoint(from: viewPoint); let changed = objectStore.dragDynamicAngleEndpoint(id: id, to: CGPoint(x: CGFloat(p.x), y: CGFloat(p.y))); if changed { rebuildGeometry() }; return changed }
    func selectedDynamicAngleDegrees() -> CGFloat? { guard selectedObjectIDs.count == 1, let id = selectedObjectIDs.first else { return nil }; return objectStore.dynamicAngleParameter(id: id)?.value }
    @discardableResult func setSelectedDynamicAngleDegrees(_ degrees: CGFloat) -> Bool { guard selectedObjectIDs.count == 1, let id = selectedObjectIDs.first else { return false }; guard objectStore.setDynamicAngle(id: id, degrees: degrees) else { return false }; rebuildGeometry(); return true }
    func isSelectedDynamicAnglePlaying() -> Bool { guard selectedObjectIDs.count == 1, let id = selectedObjectIDs.first, let parameter = objectStore.dynamicAngleParameter(id: id) else { return false }; return dynamicAngleAnimationDriver.isPlaying(parameterID: parameter.id) }
    func toggleSelectedDynamicAnglePlayback() { guard selectedObjectIDs.count == 1, let id = selectedObjectIDs.first, let parameter = objectStore.dynamicAngleParameter(id: id) else { return }; dynamicAngleAnimationDriver.toggle(parameterID: parameter.id); if dynamicAngleAnimationDriver.isPlaying(parameterID: parameter.id) { startAnimationTimerIfNeeded() } else if !dynamicAngleAnimationDriver.isPlayingAny { animationTimer?.invalidate(); animationTimer = nil }; rebuildGeometry() }
    func stopAllDynamicAngleAnimations() { dynamicAngleAnimationDriver.stopAll(); animationTimer?.invalidate(); animationTimer = nil }
    private func startAnimationTimerIfNeeded() { guard animationTimer == nil else { return }; let timer = Timer(timeInterval: 1.0 / 30.0, repeats: true) { [weak self] timer in guard let self else { timer.invalidate(); return }; self.advanceDynamicAngleAnimation(deltaTime: 1.0 / 30.0) }; animationTimer = timer; RunLoop.main.add(timer, forMode: .common) }
    private func advanceDynamicAngleAnimation(deltaTime: CGFloat) { var changed = false; for object in objectStore.objects where object.kind == .dynamicAngle { guard var dynamic = object.dynamicAngleModel, let parameter = dynamic.parameter, dynamicAngleAnimationDriver.isPlaying(parameterID: parameter.id) else { continue }; dynamicAngleAnimationDriver.advance(model: &dynamic.model, deltaTime: deltaTime); guard let value = dynamic.model.parameter(id: parameter.id)?.value else { continue }; if objectStore.setDynamicAngle(id: object.id, degrees: value) { changed = true } }; if changed { rebuildGeometry(); attachedView?.draw() }; if !dynamicAngleAnimationDriver.isPlayingAny { animationTimer?.invalidate(); animationTimer = nil } }

    // MARK: - Dynamic isosceles triangle
    @discardableResult func commitDynamicIsoscelesTriangle(at viewPoint: SIMD2<Float>, apexAngleDegrees: CGFloat = 60) -> UUID {
        let canvas = canvasPoint(from: viewPoint); recordMutation()
        let style = GraphicObject.Style(strokeColor: penStyle.color, strokeWidth: penStyle.width, opacity: penStyle.opacity, lineStyle: penStyle.lineStyle, fillEnabled: false, fillColor: .black, fillOpacity: 0)
        let id = objectStore.addDynamicIsoscelesTriangle(anchor: CGPoint(x: CGFloat(canvas.x), y: CGFloat(canvas.y)), legLength: 150 / CGFloat(zoomScale), apexAngleDegrees: apexAngleDegrees, minimum: 30, maximum: 150, step: 1, style: style)
        selectedStrokeIndices = []; selectedObjectIDs = [id]; activeStroke = []; rebuildGeometry(); return id
    }
    func selectedDynamicIsoscelesTriangleDegrees() -> CGFloat? { guard selectedObjectIDs.count == 1, let id = selectedObjectIDs.first else { return nil }; return objectStore.triangleParameter(id: id) }
    func selectedDynamicIsoscelesTriangleLegLength() -> CGFloat? { guard selectedObjectIDs.count == 1, let id = selectedObjectIDs.first else { return nil }; return objectStore.triangleLegLength(id: id) }
    @discardableResult func setSelectedDynamicIsoscelesTriangleDegrees(_ degrees: CGFloat) -> Bool { guard selectedObjectIDs.count == 1, let id = selectedObjectIDs.first else { return false }; guard objectStore.setDynamicTriangleAngle(id: id, degrees: degrees) else { return false }; rebuildGeometry(); return true }
    @discardableResult func setSelectedDynamicIsoscelesTriangleLegLength(_ length: CGFloat) -> Bool { guard selectedObjectIDs.count == 1, let id = selectedObjectIDs.first else { return false }; guard objectStore.setDynamicTriangleLegLength(id: id, length: length) else { return false }; rebuildGeometry(); return true }
    @discardableResult func dynamicIsoscelesTriangleControlPoint(at point: SIMD2<Float>, tolerance: Float = 18) -> UUID? { guard selectedObjectIDs.count == 1, let id = selectedObjectIDs.first, let object = objectStore.object(with: id), object.kind == .parameterizedTriangle, let model = object.triangleModel else { return nil }; let raw = transformPoint(model.angleControlPoint(), by: object.transform); let handle = viewPoint(from: SIMD2(Float(raw.x), Float(raw.y))); return simd_distance(point, handle) <= tolerance ? id : nil }
    @discardableResult func moveDynamicIsoscelesTriangleControlPoint(id: UUID, to point: SIMD2<Float>) -> Bool { guard let object = objectStore.object(with: id), object.kind == .parameterizedTriangle, var model = object.triangleModel else { return false }; let canvas = canvasPoint(from: point); let raw = inverseTransformPoint(CGPoint(x: CGFloat(canvas.x), y: CGFloat(canvas.y)), by: object.transform); let dx = raw.x - model.anchor.x; let dy = raw.y - model.anchor.y; let c = cos(model.rotation); let s = sin(model.rotation); let localX = dx * c + dy * s; let localY = -dx * s + dy * c; guard hypot(localX, localY) > 0.001 else { return false }; let degrees = 2 * atan2(abs(localX), max(0.001, localY)) * 180 / .pi; model.setApexAngle(max(30, min(150, degrees))); guard objectStore.updateTriangleModel(id: id, { $0 = model }) else { return false }; rebuildGeometry(); return true }
    private func transformPoint(_ point: CGPoint, by transform: GraphicObject.Transform) -> CGPoint { let c = transform.rotationCenter; let t = CGPoint(x: point.x - c.x, y: point.y - c.y); let s = CGPoint(x: t.x * transform.scale.width, y: t.y * transform.scale.height); let co = cos(transform.rotation), si = sin(transform.rotation); return CGPoint(x: s.x * co - s.y * si + c.x + transform.position.x, y: s.x * si + s.y * co + c.y + transform.position.y) }
    private func inverseTransformPoint(_ point: CGPoint, by transform: GraphicObject.Transform) -> CGPoint { let p = CGPoint(x: point.x - transform.position.x - transform.rotationCenter.x, y: point.y - transform.position.y - transform.rotationCenter.y); let co = cos(transform.rotation), si = sin(transform.rotation); let rx = p.x * co + p.y * si; let ry = -p.x * si + p.y * co; let sx = abs(transform.scale.width) > 0.0001 ? rx / transform.scale.width : rx; let sy = abs(transform.scale.height) > 0.0001 ? ry / transform.scale.height : ry; return CGPoint(x: sx + transform.rotationCenter.x, y: sy + transform.rotationCenter.y) }

    // MARK: - Clipboard and selection
    func makeSelectionClipboardData() -> Data? { let strokes = selectedStrokeIndices.compactMap { index -> CanvasStroke? in guard committedStrokes.indices.contains(index) else { return nil }; let stroke = committedStrokes[index]; return CanvasStroke(id: stroke.id, points: stroke.points, style: stroke.style, rotation: stroke.rotation) }; let objects = selectedObjectIDs.compactMap { objectStore.object(with: $0) }; let payload = SelectionClipboardPayload(strokes: strokes, objects: objects); guard !payload.isEmpty, let data = try? JSONEncoder().encode(payload) else { return nil }; pasteCascadeIndex = 0; lastClipboardPayloadData = data; return data }
    @discardableResult func pasteSelectionClipboardData(_ data: Data) -> Bool { guard let payload = try? JSONDecoder().decode(SelectionClipboardPayload.self, from: data), payload.version == SelectionClipboardPayload.currentVersion, !payload.isEmpty else { return false }; if lastClipboardPayloadData != data { pasteCascadeIndex = 0; lastClipboardPayloadData = data }; pasteCascadeIndex += 1; let screenOffset: Float = 24; let canvasOffset = screenOffset / max(zoomScale, 0.001); let delta = CGPoint(x: CGFloat(canvasOffset * Float(pasteCascadeIndex)), y: CGFloat(canvasOffset * Float(pasteCascadeIndex))); recordMutation(); let strokeStartIndex = committedStrokes.count; for stroke in payload.strokes { let shiftedPoints = stroke.points.map { InkPoint(x: $0.x + Float(delta.x), y: $0.y + Float(delta.y), pressure: $0.pressure) }; committedStrokes.append(StoredStroke(id: UUID(), points: shiftedPoints, style: stroke.style, rotation: stroke.rotation) ) }; var pastedObjectIDs: [UUID] = []; for object in payload.objects { let duplicated = duplicateObject(object, topLevelOffset: delta); pastedObjectIDs.append(duplicated.id); objectStore.update(duplicated) }; selectedStrokeIndices = Array(strokeStartIndex..<committedStrokes.count); selectedObjectIDs = pastedObjectIDs; customRotationCenter = nil; activeStroke = []; rebuildGeometry(); return true }
    private func duplicateObject(_ object: GraphicObject, topLevelOffset: CGPoint) -> GraphicObject { let children = object.children.map { duplicateObject($0, topLevelOffset: .zero) }; var transform = object.transform; transform.position.x += topLevelOffset.x; transform.position.y += topLevelOffset.y; return GraphicObject(id: UUID(), kind: object.kind, transform: transform, style: object.style, geometry: object.geometry, children: children, geometryModel: object.geometryModel, triangleModel: object.triangleModel, dynamicAngleModel: object.dynamicAngleModel) }
    private func applySelection(_ operation: SelectionOperation, objects: [UUID], strokes: [Int]) { switch operation { case .replace: selectedObjectIDs = objects; selectedStrokeIndices = strokes; case .add: for id in objects where !selectedObjectIDs.contains(id) { selectedObjectIDs.append(id) }; for index in strokes where !selectedStrokeIndices.contains(index) { selectedStrokeIndices.append(index) }; case .subtract: selectedObjectIDs.removeAll { objects.contains($0) }; selectedStrokeIndices.removeAll { strokes.contains($0) } }; customRotationCenter = nil; rebuildGeometry() }
    @discardableResult func selectObject(at point: SIMD2<Float>, tolerance: Float = 10, operation: SelectionOperation = .replace) -> Bool { let p = canvasPoint(from: point); guard let id = objectStore.hitTest(at: CGPoint(x: CGFloat(p.x), y: CGFloat(p.y)), tolerance: CGFloat(tolerance / zoomScale)) else { if operation == .replace { clearSelection() }; return false }; applySelection(operation, objects: [id], strokes: []); return true }
    @discardableResult func toggleObject(at point: SIMD2<Float>, tolerance: Float = 10) -> Bool { let p = canvasPoint(from: point); guard let id = objectStore.hitTest(at: CGPoint(x: CGFloat(p.x), y: CGFloat(p.y)), tolerance: CGFloat(tolerance / zoomScale)) else { return false }; if selectedObjectIDs.contains(id) { selectedObjectIDs.removeAll { $0 == id } } else { selectedObjectIDs.append(id) }; customRotationCenter = nil; rebuildGeometry(); return true }
    @discardableResult func selectObjects(in viewRect: CGRect, fullyContained: Bool = false, operation: SelectionOperation = .replace) -> Int { let a = canvasPoint(from: SIMD2(Float(viewRect.minX),Float(viewRect.minY))); let b = canvasPoint(from: SIMD2(Float(viewRect.maxX),Float(viewRect.maxY))); let r = CGRect(x: CGFloat(min(a.x,b.x)), y: CGFloat(min(a.y,b.y)), width: CGFloat(abs(a.x-b.x)), height: CGFloat(abs(a.y-b.y))); let ids = objectStore.objectsIntersecting(r, fullyContained: fullyContained); applySelection(operation, objects: ids, strokes: []); return selectionCount }
    @discardableResult func lineEndpoint(at point: SIMD2<Float>, tolerance: Float = 14) -> (id: UUID, endpoint: Int)? { let p = canvasPoint(from: point); guard let hit = objectStore.nearestLineEndpoint(to: CGPoint(x: CGFloat(p.x), y: CGFloat(p.y)), tolerance: CGFloat(tolerance / zoomScale)) else { return nil }; return (hit.id, hit.endpoint) }
    @discardableResult func moveSelectedLineEndpoint(id: UUID, endpoint: Int, to point: SIMD2<Float>) -> Bool { let p = canvasPoint(from: point); guard objectStore.moveLineEndpointResolved(id: id, endpoint: endpoint, to: CGPoint(x: CGFloat(p.x), y: CGFloat(p.y))) else { return false }; rebuildGeometry(); return true }
    @discardableResult func polygonVertex(at point: SIMD2<Float>, tolerance: Float = 14) -> (id: UUID, vertexIndex: Int)? { guard selectedObjectIDs.count == 1, let selectedID = selectedObjectIDs.first, let object = objectStore.object(with: selectedID), object.kind == .polygon else { return nil }; let p = canvasPoint(from: point); guard let hit = objectStore.nearestPolygonVertex(to: CGPoint(x: CGFloat(p.x), y: CGFloat(p.y)), tolerance: CGFloat(tolerance / zoomScale)) else { return nil }; guard hit.id == selectedID else { return nil }; return (hit.id, hit.index) }
    @discardableResult func moveSelectedPolygonVertex(id: UUID, vertexIndex: Int, to point: SIMD2<Float>) -> Bool { guard selectedObjectIDs.count == 1, selectedObjectIDs.first == id else { return false }; let p = canvasPoint(from: point); guard objectStore.movePolygonVertex(id: id, index: vertexIndex, to: CGPoint(x: CGFloat(p.x), y: CGFloat(p.y))) else { return false }; rebuildGeometry(); return true }
    func deleteSelectedObjects() { guard !selectedObjectIDs.isEmpty else { return }; recordMutation(); for id in selectedObjectIDs { objectStore.remove(id: id) }; selectedObjectIDs = []; rebuildGeometry() }
    @discardableResult func eraseObjectsByScribble(_ path: [SIMD2<Float>], tolerance: Float = 12) -> Bool { let p = path.map { let q = canvasPoint(from: $0); return CGPoint(x: CGFloat(q.x), y: CGFloat(q.y)) }; let ids = objectStore.eraseByScribble(p, tolerance: CGFloat(tolerance / zoomScale)); guard !ids.isEmpty else { return false }; selectedObjectIDs.removeAll { ids.contains($0) }; rebuildGeometry(); return true }
    private func strokeHit(at point: SIMD2<Float>, tolerance: Float) -> Int? { let p = canvasPoint(from: point); var hit: Int?; var best = tolerance / zoomScale; for i in committedStrokes.indices.reversed() { let s = committedStrokes[i].points; guard s.count > 1 else { continue }; for j in 0..<(s.count-1) { let d = distance(p, SIMD2(s[j].x,s[j].y), SIMD2(s[j+1].x,s[j+1].y)); if d <= best { best = d; hit = i; break } } }; return hit }
    @discardableResult func selectStroke(at point: SIMD2<Float>, tolerance: Float = 10, operation: SelectionOperation = .replace) -> Bool { guard let hit = strokeHit(at: point, tolerance: tolerance) else { if operation == .replace { clearSelection() }; return false }; applySelection(operation, objects: [], strokes: [hit]); return true }
    @discardableResult func toggleStroke(at point: SIMD2<Float>, tolerance: Float = 10) -> Bool { guard let hit = strokeHit(at: point, tolerance: tolerance) else { return false }; if selectedStrokeIndices.contains(hit) { selectedStrokeIndices.removeAll { $0 == hit } } else { selectedStrokeIndices.append(hit) }; customRotationCenter = nil; rebuildGeometry(); return true }
    @discardableResult func selectStrokes(in viewRect: CGRect, fullyContained: Bool = false, operation: SelectionOperation = .replace) -> Int { let a = canvasPoint(from: SIMD2(Float(viewRect.minX),Float(viewRect.minY))); let b = canvasPoint(from: SIMD2(Float(viewRect.maxX),Float(viewRect.maxY))); let r = CGRect(x: CGFloat(min(a.x,b.x)), y: CGFloat(min(a.y,b.y)), width: CGFloat(abs(a.x-b.x)), height: CGFloat(abs(a.y-b.y))); let result = committedStrokes.indices.filter { guard let b = bounds(committedStrokes[$0].points) else { return false }; return fullyContained ? r.contains(b) : r.intersects(b) }; applySelection(operation, objects: [], strokes: Array(result)); return selectionCount }
    @discardableResult func selectLasso(in viewPoints: [SIMD2<Float>], operation: SelectionOperation = .replace) -> Int { guard viewPoints.count >= 3 else { if operation == .replace { clearSelection() }; return selectionCount }; let lasso = viewPoints.map { p in let c = canvasPoint(from: p); return CGPoint(x: CGFloat(c.x), y: CGFloat(c.y)) }; let objects = objectStore.objectsIntersectingLasso(lasso); let strokes = committedStrokes.indices.filter { strokeIntersectsLasso(committedStrokes[$0].points, lasso) }; applySelection(operation, objects: objects, strokes: Array(strokes)); return selectionCount }
    func clearSelection() { selectedStrokeIndices = []; selectedObjectIDs = []; customRotationCenter = nil; rebuildGeometry() }
    func selectionBounds() -> CGRect? { var result:CGRect?; for i in selectedStrokeIndices { if committedStrokes.indices.contains(i), let b=bounds(committedStrokes[i].points) { result=result?.union(b) ?? b } }; for id in selectedObjectIDs { if let b=objectStore.bounds(of:id) { result=result?.union(b) ?? b } }; return result?.insetBy(dx:-8,dy:-8) }
    func selectionBoundsInView() -> CGRect? { guard let r=selectionBounds() else { return nil }; let a=viewPoint(from:SIMD2(Float(r.minX),Float(r.minY))),b=viewPoint(from:SIMD2(Float(r.maxX),Float(r.maxY))); return CGRect(x:CGFloat(min(a.x,b.x)),y:CGFloat(min(a.y,b.y)),width:CGFloat(abs(b.x-a.x)),height:CGFloat(abs(b.y-a.y))) }
    func selectionCenter() -> SIMD2<Float>? { guard let r=selectionBounds() else { return nil }; return SIMD2(Float(r.midX),Float(r.midY)) }
    func setRotationCenter(to point: SIMD2<Float>) { let requested=canvasPoint(from:point); let tolerance=CGFloat(18/max(zoomScale,0.001)); var bestPoint:CGPoint?; var bestDistance=tolerance; for object in objectStore.objects { let transformed=objectStore.transformedPoints(of:object); guard !transformed.isEmpty else { continue }; for vertex in transformed { let d=hypot(vertex.x-CGFloat(requested.x),vertex.y-CGFloat(requested.y)); if d<bestDistance { bestDistance=d; bestPoint=vertex } }; if transformed.count>=2 { let closed=object.kind == .polygon || object.kind == .parameterizedTriangle; let pairs=closed ? zip(transformed,Array(transformed.dropFirst())+[transformed[0]]) : zip(transformed,transformed.dropFirst()); for pair in pairs { let a=pair.0,b=pair.1,dx=b.x-a.x,dy=b.y-a.y,len2=dx*dx+dy*dy; if len2<=0.0001 { continue }; let t=max(0,min(1,((requested.x-CGFloat(a.x))*dx+(requested.y-CGFloat(a.y))*dy)/len2)); let candidate=CGPoint(x:a.x+t*dx,y:a.y+t*dy); let d=hypot(candidate.x-CGFloat(requested.x),candidate.y-CGFloat(requested.y)); if d<bestDistance { bestDistance=d; bestPoint=candidate } } } }; customRotationCenter=bestPoint.map{SIMD2(Float($0.x),Float($0.y))} ?? requested; rebuildGeometry() }
    func rotationCenterViewPoint() -> SIMD2<Float>? { guard let c=customRotationCenter ?? selectionCenter() else { return nil }; return viewPoint(from:c) }
    func selectionHandle(at point:SIMD2<Float>,tolerance:Float=10)->SelectionHandle? { guard selectionCount>1,let r=selectionBounds() else{return nil};let p=canvasPoint(from:point),t=tolerance/zoomScale;let h:[(SelectionHandle,SIMD2<Float>)]=[(.topRight,SIMD2(Float(r.maxX),Float(r.minY))),(.bottomRight,SIMD2(Float(r.maxX),Float(r.maxY)))];return h.first{simd_distance(p,$0.1)<=t}?.0 }
    func rotationHandle(at point:SIMD2<Float>,tolerance:Float=12)->Bool { guard selectionCount>1,let r=selectionBounds() else{return false};let p=canvasPoint(from:point);return simd_distance(p,SIMD2(Float(r.maxX),Float(r.minY)))<=tolerance/zoomScale }
    func rotationCenterHandle(at point:SIMD2<Float>,tolerance:Float=12)->Bool { guard let c=rotationCenterViewPoint() else{return false};return simd_distance(point,c)<=tolerance }
    func selectionMoveHandle(at point:SIMD2<Float>,tolerance:Float=10)->Bool { guard selectionCount>1,let r=selectionBoundsInView() else{return false};let p=CGPoint(x:CGFloat(point.x),y:CGFloat(point.y));let edgeTolerance=CGFloat(tolerance);let nearTop=abs(p.y-r.minY)<=edgeTolerance && p.x>r.minX+28 && p.x<r.maxX-28;let nearBottom=abs(p.y-r.maxY)<=edgeTolerance && p.x>r.minX+28 && p.x<r.maxX-28;let nearLeft=abs(p.x-r.minX)<=edgeTolerance && p.y>r.minY+28 && p.y<r.maxY-28;let nearRight=abs(p.x-r.maxX)<=edgeTolerance && p.y>r.minY+28 && p.y<r.maxY-28;return nearTop||nearBottom||nearLeft||nearRight }
    func resizeSelected(handle:SelectionHandle,to point:SIMD2<Float>) { guard let r=selectionBounds() else{return};let p=canvasPoint(from:point);let anchor:SIMD2<Float>;switch handle{case.topRight:anchor=SIMD2(Float(r.minX),Float(r.maxY));case.bottomRight:anchor=SIMD2(Float(r.minX),Float(r.minY))};let sx=max(abs(p.x-anchor.x),1)/max(Float(r.width),1);let sy=max(abs(p.y-anchor.y),1)/max(Float(r.height),1);for i in selectedStrokeIndices where committedStrokes.indices.contains(i){committedStrokes[i].points=committedStrokes[i].points.map{InkPoint(x:anchor.x+($0.x-anchor.x)*sx,y:anchor.y+($0.y-anchor.y)*sy,pressure:$0.pressure)}};for id in selectedObjectIDs{guard let o=objectStore.object(with:id)else{continue};let transformed=objectStore.transformedPoints(of:o);guard let b=transformed.reduce(nil,{(current:CGRect?,point:CGPoint)->CGRect? in current?.union(CGRect(origin:point,size:.zero)) ?? CGRect(origin:point,size:.zero)})else{continue};let oldCenter=SIMD2(Float(b.midX),Float(b.midY));let newCenter=SIMD2(anchor.x+(oldCenter.x-anchor.x)*sx,anchor.y+(oldCenter.y-anchor.y)*sy);let s=o.transform.scale;_=objectStore.transform(id:id,position:CGPoint(x:CGFloat(newCenter.x),y:CGFloat(newCenter.y)),scale:CGSize(width:s.width*CGFloat(sx),height:s.height*CGFloat(sy)))};rebuildGeometry()}
    func scaleSelected(by factor:Float){guard factor>0,let c=selectionCenter()else{return};for i in selectedStrokeIndices where committedStrokes.indices.contains(i){committedStrokes[i].points=committedStrokes[i].points.map{InkPoint(x:c.x+($0.x-c.x)*factor,y:c.y+($0.y-c.y)*factor,pressure:$0.pressure)}};for id in selectedObjectIDs{guard let o=objectStore.object(with:id)else{continue};let p=o.transform.position;let np=SIMD2(Float(p.x),Float(p.y));let moved=c+(np-c)*factor;let s=o.transform.scale;_=objectStore.transform(id:id,position:CGPoint(x:CGFloat(moved.x),y:CGFloat(moved.y)),scale:CGSize(width:s.width*CGFloat(factor),height:s.height*CGFloat(factor)))};rebuildGeometry()}
    func moveSelected(by delta:SIMD2<Float>){for id in selectedObjectIDs{guard let o=objectStore.object(with:id)else{continue};let p=o.transform.position;_=objectStore.transform(id:id,position:CGPoint(x:p.x+CGFloat(delta.x),y:p.y+CGFloat(delta.y)))};for i in selectedStrokeIndices where committedStrokes.indices.contains(i){committedStrokes[i].points=committedStrokes[i].points.map{InkPoint(x:$0.x+delta.x,y:$0.y+delta.y,pressure:$0.pressure)}};rebuildGeometry()}
    func rotateSelected(to point:SIMD2<Float>,from previous:SIMD2<Float>){guard let c=customRotationCenter ?? selectionCenter()else{return};let p=canvasPoint(from:point),q=canvasPoint(from:previous);rotateSelected(by:atan2(p.y-c.y,p.x-c.x)-atan2(q.y-c.y,q.x-c.x),center:c)}
    func setSelectedRotationDegrees(_ degrees:Double){guard let c=selectionCenter()else{return};rotateSelected(by:Float(degrees-selectedRotationDegrees)*Float.pi/180,center:c)}
    private func rotateSelected(by d:Float,center c:SIMD2<Float>){let co=cos(d),si=sin(d);for i in selectedStrokeIndices where committedStrokes.indices.contains(i){committedStrokes[i].points=committedStrokes[i].points.map{let v=SIMD2($0.x,$0.y)-c;return InkPoint(x:v.x*co-v.y*si+c.x,y:v.x*si+v.y*co+c.y,pressure:$0.pressure)};committedStrokes[i].rotation += d};for id in selectedObjectIDs{guard let o=objectStore.object(with:id)else{continue};let p=SIMD2(Float(o.transform.position.x),Float(o.transform.position.y))-c;let moved=SIMD2(p.x*co-p.y*si,p.x*si+p.y*co)+c;_=objectStore.transform(id:id,position:CGPoint(x:CGFloat(moved.x),y:CGFloat(moved.y)),rotation:o.transform.rotation+CGFloat(d))};rebuildGeometry()}
    func reflectSelected(horizontal:Bool){guard let c=selectionCenter()else{return};for i in selectedStrokeIndices where committedStrokes.indices.contains(i){committedStrokes[i].points=committedStrokes[i].points.map{horizontal ? InkPoint(x:2*c.x-$0.x,y:$0.y,pressure:$0.pressure):InkPoint(x:$0.x,y:2*c.y-$0.y,pressure:$0.pressure)}};for id in selectedObjectIDs{guard let o=objectStore.object(with:id)else{continue};let p=o.transform.position;let reflected=horizontal ? SIMD2(2*c.x-Float(p.x),Float(p.y)):SIMD2(Float(p.x),2*c.y-Float(p.y));let s=o.transform.scale;_=objectStore.transform(id:id,position:CGPoint(x:CGFloat(reflected.x),y:CGFloat(reflected.y)),scale:CGSize(width:horizontal ? -s.width:s.width,height:horizontal ? s.height:-s.height))};rebuildGeometry()}
    func deleteSelected(){guard hasSelection else{return};recordMutation();for id in selectedObjectIDs{objectStore.remove(id:id)};for i in selectedStrokeIndices.sorted(by:> ) where committedStrokes.indices.contains(i){committedStrokes.remove(at:i)};selectedObjectIDs=[];selectedStrokeIndices=[];customRotationCenter=nil;rebuildGeometry()}

    func mtkView(_ view:MTKView,drawableSizeWillChange size:CGSize){attachedView=view;updateUniformBuffer(for:view.bounds.size)}
    func draw(in view:MTKView){attachedView=view;guard let pass=view.currentRenderPassDescriptor,let drawable=view.currentDrawable,let cb=commandQueue.makeCommandBuffer(),let encoder=cb.makeRenderCommandEncoder(descriptor:pass)else{return};pass.colorAttachments[0].clearColor=MTLClearColor(red:Double(backgroundColor.x),green:Double(backgroundColor.y),blue:Double(backgroundColor.z),alpha:1);updateUniformBuffer(for:view.bounds.size);encoder.setRenderPipelineState(pipelineState);if let b=vertexBuffer{encoder.setVertexBuffer(b,offset:0,index:0)};if let b=uniformBuffer{encoder.setVertexBuffer(b,offset:0,index:1)};if !vertices.isEmpty{encoder.drawPrimitives(type:.triangle,vertexStart:0,vertexCount:vertices.count)};encoder.endEncoding();cb.present(drawable);cb.commit()}
    private func rebuildGeometry(){var out:[InkVertex]=[];appendBackground(to:&out);for s in committedStrokes{appendStroke(s.points,style:s.style,to:&out)};appendObjects(to:&out);if selectionCount>1,let r=selectionBounds(){appendSelection(r,to:&out)}else{appendSingleSelectionControls(to:&out)};if !activeStroke.isEmpty{appendStroke(activeStroke,style:penStyle,to:&out)};vertices=out;vertexBuffer=vertices.isEmpty ? nil : device.makeBuffer(bytes:vertices,length:vertices.count*MemoryLayout<InkVertex>.stride,options:.storageModeShared)}
    private func appendObjects(to out:inout[InkVertex]){for o in objectStore.objects{let p=objectStore.transformedPoints(of:o);guard !p.isEmpty else{continue};let color=metalColor(o.style);if o.kind == .geometryPoint{disk(viewPoint(from:SIMD2(Float(p[0].x),Float(p[0].y))),6,color,to:&out)}else if o.kind == .line || o.kind == .arrow{guard p.count>=2 else{continue};appendLine(viewPoint(from:SIMD2(Float(p[0].x),Float(p[0].y))),viewPoint(from:SIMD2(Float(p[1].x),Float(p[1].y))),width:Float(max(0.5,o.style.strokeWidth)),color:color,to:&out)}else if o.kind == .polygon{let limit=p.count;if limit>=2{for i in 0..<limit{let j=(i+1)%limit;appendLine(viewPoint(from:SIMD2(Float(p[i].x),Float(p[i].y))),viewPoint(from:SIMD2(Float(p[j].x),Float(p[j].y))),width:Float(max(0.5,o.style.strokeWidth)),color:color,to:&out)}}}else if o.kind == .parameterizedTriangle{let limit=min(3,p.count);if limit==3{for i in 0..<3{let j=(i+1)%3;appendLine(viewPoint(from:SIMD2(Float(p[i].x),Float(p[i].y))),viewPoint(from:SIMD2(Float(p[j].x),Float(p[j].y))),width:Float(max(0.5,o.style.strokeWidth)),color:color,to:&out)}}}else if o.kind == .dynamicAngle{appendDynamicAngle(o,points:p,color:color,to:&out)}}}
    private func appendDynamicAngle(_ object:GraphicObject,points:[CGPoint],color:SIMD4<Float>,to out:inout[InkVertex]){guard let model=object.dynamicAngleModel,let vertex=model.model.points.first(where:{$0.id==model.vertexPointID}),let start=model.model.points.first(where:{$0.id==model.startPointID}),let end=model.model.points.first(where:{$0.id==model.endPointID}),points.count>=3 else{return};let v=viewPoint(from:SIMD2(Float(vertex.position.x),Float(vertex.position.y)));let s=viewPoint(from:SIMD2(Float(start.position.x),Float(start.position.y)));let e=viewPoint(from:SIMD2(Float(end.position.x),Float(end.position.y)));let lineWidth=Float(max(0.5,object.style.strokeWidth));appendLine(v,s,width:lineWidth,color:color,to:&out);appendLine(v,e,width:lineWidth,color:color,to:&out);let startAngle=atan2(s.y-v.y,s.x-v.x);let endAngle=atan2(e.y-v.y,e.x-v.x);let cross=(s.x-v.x)*(e.y-v.y)-(s.y-v.y)*(e.x-v.x);let signed:CGFloat=cross>=0 ? 1:-1;var delta=abs(endAngle-startAngle);if delta > .pi{delta=2*.pi-delta};let sourceRadius=hypot(s.x-v.x,s.y-v.y);let radius=min(CGFloat(60),max(CGFloat(18),sourceRadius*CGFloat(0.32)));let segmentCount=max(12,Int((delta*CGFloat(180.0/.pi))/CGFloat(4.0)));let angleStep=delta/CGFloat(segmentCount);var previous=v+SIMD2(cos(startAngle),sin(startAngle))*Float(radius);for index in 1...segmentCount{let offset=angleStep*CGFloat(index);let signedOffset=signed*offset;let angle=startAngle+signedOffset;let arcVector=SIMD2<Float>(Float(cos(angle)),Float(sin(angle)));let current=v+arcVector*Float(radius);appendLine(previous,current,width:Float(max(1.0,object.style.strokeWidth*0.9)),color:color,to:&out);previous=current};if selectedObjectIDs.contains(object.id){disk(v,6,SIMD4(0.1,0.45,1,0.9),to:&out);disk(e,7,SIMD4(0.95,0.55,0.05,1),to:&out)}}
    private func appendBackground(to out:inout[InkVertex]){guard backgroundPattern != 0 else{return};let color=SIMD4(0.82,0.84,0.88,0.55);let step:Float=backgroundPattern == 3 ? 24:32;let e:Float=2000;if backgroundPattern == 1{var y:Float = -e;while y<=e{appendLine(viewPoint(from:SIMD2(-e,y)),viewPoint(from:SIMD2(e,y)),width:0.55,color:color,to:&out);y+=step}}else{var x:Float = -e;while x<=e{appendLine(viewPoint(from:SIMD2(x,-e)),viewPoint(from:SIMD2(x,e)),width:0.45,color:color,to:&out);x+=step};var y:Float = -e;while y<=e{appendLine(viewPoint(from:SIMD2(-e,y)),viewPoint(from:SIMD2(e,y)),width:0.45,color:color,to:&out);y+=step}}
    private func appendStroke(_ s:[InkPoint],style:PenStyle,to out:inout[InkVertex]){guard !s.isEmpty else{return};let color=metalColor(style);if s.count>1{for i in 0..<(s.count-1){let p=s[i],q=s[i+1],dx=q.x-p.x,dy=q.y-p.y,l=max(sqrt(dx*dx+dy*dy),0.001),nx=-dy/l,ny=dx/l,w0=strokeWidth(p.pressure,style),w1=strokeWidth(q.pressure,style),a=viewPoint(from:SIMD2(p.x+nx*w0,p.y+ny*w0)),b=viewPoint(from:SIMD2(p.x-nx*w0,p.y-ny*w0)),c=viewPoint(from:SIMD2(q.x+nx*w1,q.y+ny*w1)),d=viewPoint(from:SIMD2(q.x-nx*w1,q.y-ny*w1));triangle(a,b,c,color:color,to:&out);triangle(c,b,d,color:color,to:&out)}};for p in s{disk(viewPoint(from:SIMD2(p.x,p.y)),strokeWidth(p.pressure,style),color,to:&out)}}
    private func appendSelection(_ r:CGRect,to out:inout[InkVertex]){let c=SIMD4(0.1,0.45,1,0.75),a=viewPoint(from:SIMD2(Float(r.minX),Float(r.minY))),b=viewPoint(from:SIMD2(Float(r.maxX),Float(r.maxY))),p0=SIMD2(a.x,a.y),p1=SIMD2(b.x,a.y),p2=SIMD2(b.x,b.y),p3=SIMD2(a.x,b.y);appendDashedLine(p0,p1,width:1.5,color:c,to:&out);appendDashedLine(p1,p2,width:1.5,color:c,to:&out);appendDashedLine(p2,p3,width:1.5,color:c,to:&out);appendDashedLine(p3,p0,width:1.5,color:c,to:&out);let rot=p1;disk(rot,8,c,to:&out);let scale=p2;disk(scale,8,c,to:&out);if let rc=rotationCenterViewPoint(){disk(rc,7,SIMD4(0.95,0.55,0.05,1),to:&out)}}
    private func appendSingleSelectionControls(to out:inout[InkVertex]){guard selectionCount==1 else{return};let c=SIMD4(0.1,0.45,1,0.85);if let id=selectedObjectIDs.first,let o=objectStore.object(with:id){switch o.kind{case .line,.arrow:for q in objectStore.transformedPoints(of:o).prefix(2){disk(viewPoint(from:SIMD2(Float(q.x),Float(q.y))),7,c,to:&out)};case .polygon:for q in objectStore.transformedPoints(of:o){disk(viewPoint(from:SIMD2(Float(q.x),Float(q.y))),6,c,to:&out)};case .parameterizedTriangle:if let model=o.triangleModel{for q in objectStore.transformedPoints(of:o){disk(viewPoint(from:SIMD2(Float(q.x),Float(q.y))),6,c,to:&out)};let raw=transformPoint(model.angleControlPoint(),by:o.transform);disk(viewPoint(from:SIMD2(Float(raw.x),Float(raw.y))),7,SIMD4(0.95,0.55,0.05,1),to:&out);let leg=transformPoint(model.legLengthControlPoint(),by:o.transform);disk(viewPoint(from:SIMD2(Float(leg.x),Float(leg.y))),7,SIMD4(0.95,0.55,0.05,1),to:&out)};case .dynamicAngle:break;default:break}}else if let index=selectedStrokeIndex,committedStrokes.indices.contains(index),let b=bounds(committedStrokes[index].points){let a=SIMD2(Float(b.minX),Float(b.minY)),d=SIMD2(Float(b.maxX),Float(b.maxY));disk(viewPoint(from:a),6,c,to:&out);disk(viewPoint(from:d),6,c,to:&out)}}
    private func appendDashedLine(_ a:SIMD2<Float>,_ b:SIMD2<Float>,width:Float,color:SIMD4<Float>,to out:inout[InkVertex]){let d=b-a;let l=simd_length(d);guard l>0.001 else{return};let dir=d/l;let dash:Float=8;let gap:Float=5;var start:Float=0;while start<l{let end=min(start+dash,l);appendLine(a+dir*start,a+dir*end,width:width,color:color,to:&out);start=end+gap}}
    private func bounds(_ p:[InkPoint])->CGRect?{guard let f=p.first else{return nil};var x0=f.x,x1=f.x,y0=f.y,y1=f.y;for q in p{x0=min(x0,q.x);x1=max(x1,q.x);y0=min(y0,q.y);y1=max(y1,q.y)};return CGRect(x:CGFloat(x0),y:CGFloat(y0),width:CGFloat(x1-x0),height:CGFloat(y1-y0))}
    private func strokeIntersectsLasso(_ stroke:[InkPoint],_ lasso:[CGPoint])->Bool{guard stroke.count>=2,lasso.count>=3 else{return false};if stroke.contains(where:{pointInPolygon(CGPoint(x:CGFloat($0.x),y:CGFloat($0.y)),lasso)}){return true};for pair in zip(stroke,stroke.dropFirst()){let a=CGPoint(x:CGFloat(pair.0.x),y:CGFloat(pair.0.y)),b=CGPoint(x:CGFloat(pair.1.x),y:CGFloat(pair.1.y));if segmentIntersectsPolygon(a,b,lasso){return true}};return false}
    private func pointInPolygon(_ p:CGPoint,_ poly:[CGPoint])->Bool{var inside=false;var j=poly.count-1;for i in poly.indices{let a=poly[i],b=poly[j];if(a.y>p.y) != (b.y>p.y){let d=b.y-a.y;if d != 0{let x=(b.x-a.x)*(p.y-a.y)/d+a.x;if p.x<x{inside.toggle()}}};j=i};return inside}
    private func segmentIntersectsPolygon(_ a:CGPoint,_ b:CGPoint,_ polygon:[CGPoint])->Bool{if pointInPolygon(a,polygon)||pointInPolygon(b,polygon){return true};var edges=Array(polygon.dropFirst());edges.append(polygon[0]);return zip(polygon,edges).contains{segmentsIntersect(a,b,$0.0,$0.1)}}
    private func segmentsIntersect(_ a:CGPoint,_ b:CGPoint,_ c:CGPoint,_ d:CGPoint)->Bool{func cross(_ p:CGPoint,_ q:CGPoint,_ r:CGPoint)->CGFloat{(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x)};let o1=cross(a,b,c),o2=cross(a,b,d),o3=cross(c,d,a),o4=cross(c,d,b),eps:CGFloat=0.001;if abs(o1)<eps && onSegment(a,b,c){return true};if abs(o2)<eps && onSegment(a,b,d){return true};if abs(o3)<eps && onSegment(c,d,a){return true};if abs(o4)<eps && onSegment(c,d,b){return true};return(o1>0) != (o2>0) && (o3>0) != (o4>0)}
    private func onSegment(_ a:CGPoint,_ b:CGPoint,_ p:CGPoint)->Bool{p.x>=min(a.x,b.x)-0.001 && p.x<=max(a.x,b.x)+0.001 && p.y>=min(a.y,b.y)-0.001 && p.y<=max(a.y,b.y)+0.001}
    private func appendLine(_ a:SIMD2<Float>,_ b:SIMD2<Float>,width:Float,color:SIMD4<Float>,to out:inout[InkVertex]){let d=b-a,l=max(simd_length(d),0.001),n=SIMD2(-d.y,d.x)/l*width;triangle(a+n,a-n,b+n,color:color,to:&out);triangle(b+n,a-n,b-n,color:color,to:&out)}
    private func distance(_ p:SIMD2<Float>,_ a:SIMD2<Float>,_ b:SIMD2<Float>)->Float{let d=b-a,l=simd_length_squared(d);if l<0.0001{return simd_distance(p,a)};let t=max(0,min(1,simd_dot(p-a,d)/l));return simd_distance(p,a+d*t)}
    private func strokeWidth(_ pressure:Float,_ style:PenStyle)->Float{let p=max(0,min(1,pressure));let c=style.pressureEnabled ? pow(p,max(0.25,Float(style.pressureCurve))):0.75;return Float(style.width)*(0.45+0.75*c)}
    private func metalColor(_ style:PenStyle)->SIMD4<Float>{var c=SIMD4(Float(style.color.red),Float(style.color.green),Float(style.color.blue),Float(style.color.alpha*style.opacity));if displayInverted{let hi=max(c.x,max(c.y,c.z)),lo=min(c.x,min(c.y,c.z));if hi<0.12 || lo>0.88{c=SIMD4(1,1,1,c.w)}};return c}
    private func metalColor(_ style:GraphicObject.Style)->SIMD4<Float>{var c=SIMD4(Float(style.strokeColor.red),Float(style.strokeColor.green),Float(style.strokeColor.blue),Float(style.strokeColor.alpha*style.opacity));if displayInverted{let hi=max(c.x,max(c.y,c.z)),lo=min(c.x,min(c.y,c.z));if hi<0.12 || lo>0.88{c=SIMD4(1,1,1,c.w)}};return c}
    private func triangle(_ a:SIMD2<Float>,_ b:SIMD2<Float>,_ c:SIMD2<Float>,color:SIMD4<Float>,to out:inout[InkVertex]){out.append(InkVertex(position:a,color:color));out.append(InkVertex(position:b,color:color));out.append(InkVertex(position:c,color:color))}
    private func disk(_ center:SIMD2<Float>,_ radius:Float,_ color:SIMD4<Float>,to out:inout[InkVertex]){let n=12;for i in 0..<n{let a=Float(i)/Float(n)*2*Float.pi,b=Float(i+1)/Float(n)*2*Float.pi;triangle(center,center+SIMD2(cos(a),sin(a))*radius,center+SIMD2(cos(b),sin(b))*radius,color:color,to:&out)}}
    private func updateUniformBuffer(for size:CGSize){let u=Uniforms(viewportSize:SIMD2(Float(max(size.width,1)),Float(max(size.height,1))));if uniformBuffer == nil{uniformBuffer=device.makeBuffer(length:MemoryLayout<Uniforms>.stride,options:.storageModeShared)};guard let b=uniformBuffer else{return};withUnsafeBytes(of:u){if let p=$0.baseAddress{memcpy(b.contents(),p,MemoryLayout<Uniforms>.stride)}}}
}
